import { Layout } from '@/types/keyboardTypes';

export const qwertyLessons = [
    {
        title: 'F and J',
        titleRu: 'F и J',
        allowedChars: 'fj',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 1,
    },
    {
        title: 'D and K',
        titleRu: 'D и K',
        allowedChars: 'dk',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 2,
    },
    {
        title: 'S and L',
        titleRu: 'S и L',
        allowedChars: 'sl',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 3,
    },
    {
        title: 'A and ;',
        titleRu: 'A и ;',
        allowedChars: 'a;',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 4,
    },
    {
        title: 'G and H',
        titleRu: 'G и H',
        allowedChars: 'gh',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 5,
    },
    {
        title: 'T and Y',
        titleRu: 'T и Y',
        allowedChars: 'ty',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 6,
    },
    {
        title: 'B and N',
        titleRu: 'B и N',
        allowedChars: 'bn',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 7,
    },
    {
        title: 'R and U',
        titleRu: 'R и U',
        allowedChars: 'ru',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 8,
    },
    {
        title: 'V and M',
        titleRu: 'V и M',
        allowedChars: 'vm',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 9,
    },
    {
        title: 'E and I',
        titleRu: 'E и I',
        allowedChars: 'ei',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 10,
    },
    {
        title: 'C and ,',
        titleRu: 'C и ,',
        allowedChars: 'c,',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 11,
    },
    {
        title: 'W and O',
        titleRu: 'W и O',
        allowedChars: 'wo',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 12,
    },
    {
        title: 'X and .',
        titleRu: 'X и .',
        allowedChars: 'x.',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 13,
    },
    {
        title: 'Q and P',
        titleRu: 'Q и P',
        allowedChars: 'qp',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 14,
    },
    {
        title: 'Z and /',
        titleRu: 'Z и /',
        allowedChars: 'z/',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 15,
    },
    {
        title: 'Pinky reach',
        titleRu: 'Растягивание мизинца',
        allowedChars: "[]'`\\",
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 16,
    },
    {
        title: 'Top row',
        titleRu: 'Верхний ряд',
        allowedChars: 'qwertyuiop[]',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 17,
    },
    {
        title: 'Home row',
        titleRu: 'Средний ряд',
        allowedChars: "asdfghjkl;'",
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 18,
    },
    {
        title: 'Bottom row',
        titleRu: 'Нижний ряд',
        allowedChars: 'zxcvbnm,./',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 19,
    },
    {
        title: 'Numbers',
        titleRu: 'Цифры',
        allowedChars: '1234567890',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 20,
    },
    {
        title: 'Index fingers 1',
        titleRu: 'Указательные 1',
        allowedChars: 'rfvujm',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 21,
    },
    {
        title: 'Index fingers 2',
        titleRu: 'Указательные 2',
        allowedChars: 'rtfgvbyuhjnm',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 22,
    },
    {
        title: 'Index fingers 3',
        titleRu: 'Указательные 3',
        allowedChars: '4567rtyufghjvbnm',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 23,
    },
    {
        title: 'Middle fingers 1',
        titleRu: 'Средние 1',
        allowedChars: 'eidkc,',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 24,
    },
    {
        title: 'Middle fingers 2',
        titleRu: 'Средние 2',
        allowedChars: '38kidkc,',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 25,
    },
    {
        title: 'Ring fingers 1',
        titleRu: 'Безымянные 1',
        allowedChars: 'wolsx.',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 26,
    },
    {
        title: 'Ring fingers 2',
        titleRu: 'Безымянные 2',
        allowedChars: '29owlsx.',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 27,
    },
    {
        title: 'Pinky fingers 1',
        titleRu: 'Мизинцы 1',
        allowedChars: 'pqa;z/',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 28,
    },
    {
        title: 'Pinky fingers 2',
        titleRu: 'Мизинцы 2',
        allowedChars: '1qaz0p;/',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 29,
    },
    {
        title: 'Pinky fingers 3',
        titleRu: 'Мизинцы 3',
        allowedChars: "`1qaz/;'p[0-=]",
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 30,
    },
    {
        title: 'Special symbols 1',
        titleRu: 'Спецсимволы 1',
        allowedChars: '!@#$%^&*()-=_+',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 31,
    },
    {
        title: 'Special symbols 2',
        titleRu: 'Спецсимволы 2',
        allowedChars: '`~!@#$%^&*()-=_+,.;:/',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 32,
    },
    {
        title: 'Special symbols 3',
        titleRu: 'Спецсимволы 3',
        allowedChars: '`~!@#$%^&*()-=_+,.;:/[]\'{}"\\|',
        length: 120,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 33,
    },
];

export const ycukenLessons = [
    {
        title: 'A and O',
        titleRu: 'А и О',
        allowedChars: 'ао',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 1,
    },
    {
        title: 'V and L',
        titleRu: 'В и Л',
        allowedChars: 'вл',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 2,
    },
    {
        title: 'Y and D',
        titleRu: 'Ы и Д',
        allowedChars: 'ыд',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 3,
    },
    {
        title: 'F and Zh',
        titleRu: 'Ф и Ж',
        allowedChars: 'фж',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 4,
    },
    {
        title: 'P and R',
        titleRu: 'П и Р',
        allowedChars: 'пр',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 5,
    },
    {
        title: 'E and N',
        titleRu: 'Е и Н',
        allowedChars: 'ен',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 6,
    },
    {
        title: 'I and T',
        titleRu: 'И и Т',
        allowedChars: 'ит',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 7,
    },
    {
        title: 'K and G',
        titleRu: 'К и Г',
        allowedChars: 'кг',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 8,
    },
    {
        title: 'M and Ь',
        titleRu: 'М и Ь',
        allowedChars: 'мь',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 9,
    },
    {
        title: 'U and Ш',
        titleRu: 'У и Ш',
        allowedChars: 'уш',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 10,
    },
    {
        title: 'S and Б',
        titleRu: 'С и Б',
        allowedChars: 'сб',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 11,
    },
    {
        title: 'Ц and Щ',
        titleRu: 'Ц и Щ',
        allowedChars: 'цщ',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 12,
    },
    {
        title: 'Ч and Ю',
        titleRu: 'Ч и Ю',
        allowedChars: 'чю',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 13,
    },
    {
        title: 'Й and З',
        titleRu: 'Й и З',
        allowedChars: 'йз',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 14,
    },
    {
        title: 'Я and .',
        titleRu: 'Я и .',
        allowedChars: 'я.',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 15,
    },
    {
        title: 'Растягивание мизинца',
        titleRu: 'Растягивание мизинца',
        allowedChars: 'ёхъэ\\',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 16,
    },
    {
        title: 'Верхний ряд',
        titleRu: 'Верхний ряд',
        allowedChars: 'йцукенгшщзхъ',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 17,
    },
    {
        title: 'Средний ряд',
        titleRu: 'Средний ряд',
        allowedChars: 'фывапролджэ',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 18,
    },
    {
        title: 'Нижний ряд',
        titleRu: 'Нижний ряд',
        allowedChars: 'ячсмитьбю.',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 19,
    },
    {
        title: 'Цифры',
        titleRu: 'Цифры',
        allowedChars: '1234567890',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 20,
    },
    {
        title: 'Указательные 1',
        titleRu: 'Указательные 1',
        allowedChars: 'кгаомь',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 21,
    },
    {
        title: 'Указательные 2',
        titleRu: 'Указательные 2',
        allowedChars: 'кенгапромить',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 22,
    },
    {
        title: 'Указательные 3',
        titleRu: 'Указательные 3',
        allowedChars: '4567кенгапромить',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 23,
    },
    {
        title: 'Средние 1',
        titleRu: 'Средние 1',
        allowedChars: 'ушвлсб',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 24,
    },
    {
        title: 'Средние 3',
        titleRu: 'Средние 3',
        allowedChars: '38ушвлсб',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 25,
    },
    {
        title: 'Безымянные 1',
        titleRu: 'Безымянные 1',
        allowedChars: 'цщыдчю',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 26,
    },
    {
        title: 'Безымянные 2',
        titleRu: 'Безымянные 2',
        allowedChars: '29щцыдчю',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 27,
    },
    {
        title: 'Мизинцы 1',
        titleRu: 'Мизинцы 1',
        allowedChars: 'йзфжя.',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 28,
    },
    {
        title: 'Мизинцы 2',
        titleRu: 'Мизинцы 2',
        allowedChars: '10йзфжя.',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 29,
    },
    {
        title: 'Мизинцы 3',
        titleRu: 'Мизинцы 3',
        allowedChars: '10йзфжя.ёхъэ',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 30,
    },
    {
        title: 'Спецсимволы 1',
        titleRu: 'Спецсимволы 1',
        allowedChars: '!"№;%:?*()-=_+',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 31,
    },
    {
        title: 'Спецсимволы 2',
        titleRu: 'Спецсимволы 2',
        allowedChars: '!"№;%:?*()-=_+\\/.,',
        length: 120,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 32,
    },
];
