import { Layout } from '@/types/keyboardTypes';

export const qwertyLessons = [
    {
        title: 'F и J',
        allowedChars: 'fj',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 1,
    },
    {
        title: 'D и K',
        allowedChars: 'dk',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 2,
    },
    {
        title: 'S и L',
        allowedChars: 'sl',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 3,
    },
    {
        title: 'A и ;',
        allowedChars: 'a;',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 4,
    },
    {
        title: 'E и I',
        allowedChars: 'ei',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 5,
    },
    {
        title: 'W и O',
        allowedChars: 'wo',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 6,
    },
    {
        title: 'Q и P',
        allowedChars: 'qp',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 7,
    },
    {
        title: 'R и U',
        allowedChars: 'ru',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 8,
    },
    {
        title: 'T и Y',
        allowedChars: 'ty',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 9,
    },
    {
        title: 'Z и M',
        allowedChars: 'zm',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 10,
    },
    {
        title: 'X и N',
        allowedChars: 'xn',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 11,
    },
    {
        title: 'C и B',
        allowedChars: 'cb',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 12,
    },
    {
        title: 'V и ,',
        allowedChars: 'v,',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 13,
    },
    {
        title: 'Указательные 1',
        allowedChars: 'frvujm',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 14,
    },
    {
        title: 'Указательные 2',
        allowedChars: 'frvujmtgyhbn',
        length: 60,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 15,
    },
    {
        title: 'Указательные 3',
        allowedChars: 'frvujmtgyhbn4567',
        length: 60,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 16,
    },
    {
        title: 'Средние 1',
        allowedChars: 'deki',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 17,
    },
    {
        title: 'Средние 2',
        allowedChars: 'deki38',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 18,
    },
    {
        title: 'Безымянные 1',
        allowedChars: 'swol',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 19,
    },
    {
        title: 'Безымянные 2',
        allowedChars: 'swol29',
        length: 30,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 20,
    },
    {
        title: 'Мизинцы 1',
        allowedChars: 'aqp;zxm,',
        length: 40,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 21,
    },
    {
        title: 'Мизинцы 2',
        allowedChars: 'aqp;zxm,10[]\\',
        length: 60,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 22,
    },
    {
        title: 'Мизинцы 3',
        allowedChars: '`~!@#$%^&*()_+-=[]{}|;\':",./<>?',
        length: 60,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 23,
    },
    {
        title: 'Все буквы',
        allowedChars: 'abcdefghijklmnopqrstuvwxyz',
        length: 60,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 24,
    },
    {
        title: 'Буквы + знаки',
        allowedChars: "abcdefghijklmnopqrstuvwxyz,./;'[]\\",
        length: 60,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 25,
    },
    {
        title: 'Спецсимволы (все)',
        allowedChars: '`~!@#$%^&*()_+-=[]\\{}|;\':",./<>?',
        length: 60,
        layout: Layout.QWERTY,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 26,
    },
];

export const ycukenLessons = [
    {
        title: 'А и О',
        allowedChars: 'ао',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 1,
    },
    {
        title: 'В и Л',
        allowedChars: 'вл',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 2,
    },
    {
        title: 'Е и Д',
        allowedChars: 'ед',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 3,
    },
    {
        title: 'Ф и Ж',
        allowedChars: 'фж',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 4,
    },
    {
        title: 'Я и З',
        allowedChars: 'яз',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 5,
    },
    {
        title: 'Ч и Х',
        allowedChars: 'чх',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 6,
    },
    {
        title: 'С и Щ',
        allowedChars: 'сщ',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 7,
    },
    {
        title: 'И и Ш',
        allowedChars: 'иш',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 8,
    },
    {
        title: 'Ц и Ы',
        allowedChars: 'цы',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 9,
    },
    {
        title: 'У и Э',
        allowedChars: 'уэ',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 10,
    },
    {
        title: 'Й и Ю',
        allowedChars: 'йю',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 100,
        cpmFor2: 160,
        cpmFor3: 220,
        minAccuracy: 90,
        order: 11,
    },
    {
        title: 'Указательные 1',
        allowedChars: 'аролдшю',
        length: 35,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 12,
    },
    {
        title: 'Указательные 2',
        allowedChars: 'аролдшюпавы',
        length: 55,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 13,
    },
    {
        title: 'Указательные 3',
        allowedChars: 'аролдшюпавы4567',
        length: 60,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 14,
    },
    {
        title: 'Средние 1',
        allowedChars: 'вгтн',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 15,
    },
    {
        title: 'Средние 2',
        allowedChars: 'вгтн38',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 16,
    },
    {
        title: 'Безымянные 1',
        allowedChars: 'екеи',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 17,
    },
    {
        title: 'Безымянные 2',
        allowedChars: 'екеи29',
        length: 30,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 18,
    },
    {
        title: 'Мизинцы 1',
        allowedChars: 'йцумячжб',
        length: 40,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 19,
    },
    {
        title: 'Мизинцы 2',
        allowedChars: 'йцумячжб10ъё',
        length: 60,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 20,
    },
    {
        title: 'Мизинцы 3',
        allowedChars: '№;:?*()_+!"№;%:?*()@#',
        length: 60,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 21,
    },
    {
        title: 'Все буквы',
        allowedChars: 'йцукенгшщзхъфывапролджэячсмитьбю',
        length: 60,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 22,
    },
    {
        title: 'Буквы + знаки',
        allowedChars: 'йцукенгшщзхъфывапролджэячсмитьбю.,"',
        length: 60,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 23,
    },
    {
        title: 'Спецсимволы (все)',
        allowedChars: '№;:?*()_+!"№;%:?*()@#{}',
        length: 60,
        layout: Layout.YCUKEN,
        cpmFor1: 130,
        cpmFor2: 200,
        cpmFor3: 270,
        minAccuracy: 90,
        order: 24,
    },
];
