export const MAX_ERRORS_FOR_LESSON = 10;
export const MAX_CORRECTIONS_FOR_LESSON = 20;

export const MIN_ACCURACY_FOR_LEADERBOARD = 90;
export const MAX_CORRECTIONS_FOR_LEADERBOARD = 20;

export const MIN_ACCURACY_FOR_STATS = 50;
export const MAX_ERRORS_FOR_STATS = 20;
