export interface KeyboardKey {
    code: string;
    lower: string;
    upper: string;
    isWide?: boolean;
}

export type KeyboardLayout = KeyboardKey[][];

export const QWERTY_LAYOUT: KeyboardLayout = [
    [
        { code: 'Backquote', lower: '`', upper: '~' },
        { code: 'Digit1', lower: '1', upper: '!' },
        { code: 'Digit2', lower: '2', upper: '@' },
        { code: 'Digit3', lower: '3', upper: '#' },
        { code: 'Digit4', lower: '4', upper: '$' },
        { code: 'Digit5', lower: '5', upper: '%' },
        { code: 'Digit6', lower: '6', upper: '^' },
        { code: 'Digit7', lower: '7', upper: '&' },
        { code: 'Digit8', lower: '8', upper: '*' },
        { code: 'Digit9', lower: '9', upper: '(' },
        { code: 'Digit0', lower: '0', upper: ')' },
        { code: 'Minus', lower: '-', upper: '_' },
        { code: 'Equal', lower: '=', upper: '+' },
    ],
    [
        { code: 'KeyQ', lower: 'q', upper: 'Q' },
        { code: 'KeyW', lower: 'w', upper: 'W' },
        { code: 'KeyE', lower: 'e', upper: 'E' },
        { code: 'KeyR', lower: 'r', upper: 'R' },
        { code: 'KeyT', lower: 't', upper: 'T' },
        { code: 'KeyY', lower: 'y', upper: 'Y' },
        { code: 'KeyU', lower: 'u', upper: 'U' },
        { code: 'KeyI', lower: 'i', upper: 'I' },
        { code: 'KeyO', lower: 'o', upper: 'O' },
        { code: 'KeyP', lower: 'p', upper: 'P' },
        { code: 'BracketLeft', lower: '[', upper: '{' },
        { code: 'BracketRight', lower: ']', upper: '}' },
        { code: 'Backslash', lower: '\\', upper: '|' },
    ],
    [
        { code: 'KeyA', lower: 'a', upper: 'A' },
        { code: 'KeyS', lower: 's', upper: 'S' },
        { code: 'KeyD', lower: 'd', upper: 'D' },
        { code: 'KeyF', lower: 'f', upper: 'F' },
        { code: 'KeyG', lower: 'g', upper: 'G' },
        { code: 'KeyH', lower: 'h', upper: 'H' },
        { code: 'KeyJ', lower: 'j', upper: 'J' },
        { code: 'KeyK', lower: 'k', upper: 'K' },
        { code: 'KeyL', lower: 'l', upper: 'L' },
        { code: 'Semicolon', lower: ';', upper: ':' },
        { code: 'Quote', lower: "'", upper: '"' },
    ],
    [
        { code: 'KeyZ', lower: 'z', upper: 'Z' },
        { code: 'KeyX', lower: 'x', upper: 'X' },
        { code: 'KeyC', lower: 'c', upper: 'C' },
        { code: 'KeyV', lower: 'v', upper: 'V' },
        { code: 'KeyB', lower: 'b', upper: 'B' },
        { code: 'KeyN', lower: 'n', upper: 'N' },
        { code: 'KeyM', lower: 'm', upper: 'M' },
        { code: 'Comma', lower: ',', upper: '<' },
        { code: 'Period', lower: '.', upper: '>' },
        { code: 'Slash', lower: '/', upper: '?' },
    ],
    [{ code: 'Space', lower: ' ', upper: ' ', isWide: true }],
];

export const YCUKEN_LAYOUT: KeyboardLayout = [
    [
        { code: 'Backquote', lower: 'ё', upper: 'Ё' },
        { code: 'Digit1', lower: '1', upper: '!' },
        { code: 'Digit2', lower: '2', upper: '"' },
        { code: 'Digit3', lower: '3', upper: '№' },
        { code: 'Digit4', lower: '4', upper: ';' },
        { code: 'Digit5', lower: '5', upper: '%' },
        { code: 'Digit6', lower: '6', upper: ':' },
        { code: 'Digit7', lower: '7', upper: '?' },
        { code: 'Digit8', lower: '8', upper: '*' },
        { code: 'Digit9', lower: '9', upper: '(' },
        { code: 'Digit0', lower: '0', upper: ')' },
        { code: 'Minus', lower: '-', upper: '_' },
        { code: 'Equal', lower: '=', upper: '+' },
    ],
    [
        { code: 'KeyQ', lower: 'й', upper: 'Й' },
        { code: 'KeyW', lower: 'ц', upper: 'Ц' },
        { code: 'KeyE', lower: 'у', upper: 'У' },
        { code: 'KeyR', lower: 'к', upper: 'К' },
        { code: 'KeyT', lower: 'е', upper: 'Е' },
        { code: 'KeyY', lower: 'н', upper: 'Н' },
        { code: 'KeyU', lower: 'г', upper: 'Г' },
        { code: 'KeyI', lower: 'ш', upper: 'Ш' },
        { code: 'KeyO', lower: 'щ', upper: 'Щ' },
        { code: 'KeyP', lower: 'з', upper: 'З' },
        { code: 'BracketLeft', lower: 'х', upper: 'Х' },
        { code: 'BracketRight', lower: 'ъ', upper: 'Ъ' },
        { code: 'Backslash', lower: '\\', upper: '/' },
    ],
    [
        { code: 'KeyA', lower: 'ф', upper: 'Ф' },
        { code: 'KeyS', lower: 'ы', upper: 'Ы' },
        { code: 'KeyD', lower: 'в', upper: 'В' },
        { code: 'KeyF', lower: 'а', upper: 'А' },
        { code: 'KeyG', lower: 'п', upper: 'П' },
        { code: 'KeyH', lower: 'р', upper: 'Р' },
        { code: 'KeyJ', lower: 'о', upper: 'О' },
        { code: 'KeyK', lower: 'л', upper: 'Л' },
        { code: 'KeyL', lower: 'д', upper: 'Д' },
        { code: 'Semicolon', lower: 'ж', upper: 'Ж' },
        { code: 'Quote', lower: 'э', upper: 'Э' },
    ],
    [
        { code: 'KeyZ', lower: 'я', upper: 'Я' },
        { code: 'KeyX', lower: 'ч', upper: 'Ч' },
        { code: 'KeyC', lower: 'с', upper: 'С' },
        { code: 'KeyV', lower: 'м', upper: 'М' },
        { code: 'KeyB', lower: 'и', upper: 'И' },
        { code: 'KeyN', lower: 'т', upper: 'Т' },
        { code: 'KeyM', lower: 'ь', upper: 'Ь' },
        { code: 'Comma', lower: 'б', upper: 'Б' },
        { code: 'Period', lower: 'ю', upper: 'Ю' },
        { code: 'Slash', lower: '.', upper: ',' },
    ],
    [{ code: 'Space', lower: ' ', upper: ' ', isWide: true }],
];

export const KEYBOARD_LAYOUTS: Record<'QWERTY' | 'YCUKEN', KeyboardLayout> = {
    QWERTY: QWERTY_LAYOUT,
    YCUKEN: YCUKEN_LAYOUT,
};
