import type { Layout, LayoutKeys } from '../types';

export const QWERTY_KEYS: LayoutKeys = [
    [
        { code: 'Backquote', lower: '`', upper: '~', finger: 'left-pinky' },
        { code: 'Digit1', lower: '1', upper: '!', finger: 'left-pinky' },
        { code: 'Digit2', lower: '2', upper: '@', finger: 'left-ring' },
        { code: 'Digit3', lower: '3', upper: '#', finger: 'left-middle' },
        { code: 'Digit4', lower: '4', upper: '$', finger: 'left-index' },
        { code: 'Digit5', lower: '5', upper: '%', finger: 'left-index' },
        { code: 'Digit6', lower: '6', upper: '^', finger: 'right-index' },
        { code: 'Digit7', lower: '7', upper: '&', finger: 'right-index' },
        { code: 'Digit8', lower: '8', upper: '*', finger: 'right-middle' },
        { code: 'Digit9', lower: '9', upper: '(', finger: 'right-ring' },
        { code: 'Digit0', lower: '0', upper: ')', finger: 'right-pinky' },
        { code: 'Minus', lower: '-', upper: '_', finger: 'right-pinky' },
        { code: 'Equal', lower: '=', upper: '+', finger: 'right-pinky' },
        {
            code: 'Backspace',
            lower: '',
            upper: '',
            finger: 'right-pinky',
        },
    ],
    [
        { code: 'KeyQ', lower: 'q', upper: 'Q', finger: 'left-pinky' },
        { code: 'KeyW', lower: 'w', upper: 'W', finger: 'left-ring' },
        { code: 'KeyE', lower: 'e', upper: 'E', finger: 'left-middle' },
        { code: 'KeyR', lower: 'r', upper: 'R', finger: 'left-index' },
        { code: 'KeyT', lower: 't', upper: 'T', finger: 'left-index' },
        { code: 'KeyY', lower: 'y', upper: 'Y', finger: 'right-index' },
        { code: 'KeyU', lower: 'u', upper: 'U', finger: 'right-index' },
        { code: 'KeyI', lower: 'i', upper: 'I', finger: 'right-middle' },
        { code: 'KeyO', lower: 'o', upper: 'O', finger: 'right-ring' },
        { code: 'KeyP', lower: 'p', upper: 'P', finger: 'right-pinky' },
        { code: 'BracketLeft', lower: '[', upper: '{', finger: 'right-pinky' },
        { code: 'BracketRight', lower: ']', upper: '}', finger: 'right-pinky' },
        { code: 'Backslash', lower: '\\', upper: '|', finger: 'right-pinky' },
    ],
    [
        { code: 'KeyA', lower: 'a', upper: 'A', finger: 'left-pinky' },
        { code: 'KeyS', lower: 's', upper: 'S', finger: 'left-ring' },
        { code: 'KeyD', lower: 'd', upper: 'D', finger: 'left-middle' },
        { code: 'KeyF', lower: 'f', upper: 'F', finger: 'left-index' },
        { code: 'KeyG', lower: 'g', upper: 'G', finger: 'left-index' },
        { code: 'KeyH', lower: 'h', upper: 'H', finger: 'right-index' },
        { code: 'KeyJ', lower: 'j', upper: 'J', finger: 'right-index' },
        { code: 'KeyK', lower: 'k', upper: 'K', finger: 'right-middle' },
        { code: 'KeyL', lower: 'l', upper: 'L', finger: 'right-ring' },
        { code: 'Semicolon', lower: ';', upper: ':', finger: 'right-pinky' },
        { code: 'Quote', lower: "'", upper: '"', finger: 'right-pinky' },
    ],
    [
        { code: 'KeyZ', lower: 'z', upper: 'Z', finger: 'left-pinky' },
        { code: 'KeyX', lower: 'x', upper: 'X', finger: 'left-ring' },
        { code: 'KeyC', lower: 'c', upper: 'C', finger: 'left-middle' },
        { code: 'KeyV', lower: 'v', upper: 'V', finger: 'left-index' },
        { code: 'KeyB', lower: 'b', upper: 'B', finger: 'left-index' },
        { code: 'KeyN', lower: 'n', upper: 'N', finger: 'right-index' },
        { code: 'KeyM', lower: 'm', upper: 'M', finger: 'right-index' },
        { code: 'Comma', lower: ',', upper: '<', finger: 'right-middle' },
        { code: 'Period', lower: '.', upper: '>', finger: 'right-ring' },
        { code: 'Slash', lower: '/', upper: '?', finger: 'right-pinky' },
    ],
    [
        {
            code: 'Space',
            lower: ' ',
            upper: ' ',
            finger: 'thumb',
        },
    ],
];

export const YCUKEN_KEYS: LayoutKeys = [
    [
        { code: 'Backquote', lower: 'ё', upper: 'Ё', finger: 'left-pinky' },
        { code: 'Digit1', lower: '1', upper: '!', finger: 'left-pinky' },
        { code: 'Digit2', lower: '2', upper: '"', finger: 'left-ring' },
        { code: 'Digit3', lower: '3', upper: '№', finger: 'left-middle' },
        { code: 'Digit4', lower: '4', upper: ';', finger: 'left-index' },
        { code: 'Digit5', lower: '5', upper: '%', finger: 'left-index' },
        { code: 'Digit6', lower: '6', upper: ':', finger: 'right-index' },
        { code: 'Digit7', lower: '7', upper: '?', finger: 'right-index' },
        { code: 'Digit8', lower: '8', upper: '*', finger: 'right-middle' },
        { code: 'Digit9', lower: '9', upper: '(', finger: 'right-ring' },
        { code: 'Digit0', lower: '0', upper: ')', finger: 'right-pinky' },
        { code: 'Minus', lower: '-', upper: '_', finger: 'right-pinky' },
        { code: 'Equal', lower: '=', upper: '+', finger: 'right-pinky' },
        {
            code: 'Backspace',
            lower: '',
            upper: '',
            finger: 'right-pinky',
        },
    ],
    [
        { code: 'KeyQ', lower: 'й', upper: 'Й', finger: 'left-pinky' },
        { code: 'KeyW', lower: 'ц', upper: 'Ц', finger: 'left-ring' },
        { code: 'KeyE', lower: 'у', upper: 'У', finger: 'left-middle' },
        { code: 'KeyR', lower: 'к', upper: 'К', finger: 'left-index' },
        { code: 'KeyT', lower: 'е', upper: 'Е', finger: 'left-index' },
        { code: 'KeyY', lower: 'н', upper: 'Н', finger: 'right-index' },
        { code: 'KeyU', lower: 'г', upper: 'Г', finger: 'right-index' },
        { code: 'KeyI', lower: 'ш', upper: 'Ш', finger: 'right-middle' },
        { code: 'KeyO', lower: 'щ', upper: 'Щ', finger: 'right-ring' },
        { code: 'KeyP', lower: 'з', upper: 'З', finger: 'right-pinky' },
        { code: 'BracketLeft', lower: 'х', upper: 'Х', finger: 'right-pinky' },
        { code: 'BracketRight', lower: 'ъ', upper: 'Ъ', finger: 'right-pinky' },
        { code: 'Backslash', lower: '\\', upper: '/', finger: 'right-pinky' },
    ],
    [
        { code: 'KeyA', lower: 'ф', upper: 'Ф', finger: 'left-pinky' },
        { code: 'KeyS', lower: 'ы', upper: 'Ы', finger: 'left-ring' },
        { code: 'KeyD', lower: 'в', upper: 'В', finger: 'left-middle' },
        { code: 'KeyF', lower: 'а', upper: 'А', finger: 'left-index' },
        { code: 'KeyG', lower: 'п', upper: 'П', finger: 'left-index' },
        { code: 'KeyH', lower: 'р', upper: 'Р', finger: 'right-index' },
        { code: 'KeyJ', lower: 'о', upper: 'О', finger: 'right-index' },
        { code: 'KeyK', lower: 'л', upper: 'Л', finger: 'right-middle' },
        { code: 'KeyL', lower: 'д', upper: 'Д', finger: 'right-ring' },
        { code: 'Semicolon', lower: 'ж', upper: 'Ж', finger: 'right-pinky' },
        { code: 'Quote', lower: 'э', upper: 'Э', finger: 'right-pinky' },
    ],
    [
        { code: 'KeyZ', lower: 'я', upper: 'Я', finger: 'left-pinky' },
        { code: 'KeyX', lower: 'ч', upper: 'Ч', finger: 'left-ring' },
        { code: 'KeyC', lower: 'с', upper: 'С', finger: 'left-middle' },
        { code: 'KeyV', lower: 'м', upper: 'М', finger: 'left-index' },
        { code: 'KeyB', lower: 'и', upper: 'И', finger: 'left-index' },
        { code: 'KeyN', lower: 'т', upper: 'Т', finger: 'right-index' },
        { code: 'KeyM', lower: 'ь', upper: 'Ь', finger: 'right-index' },
        { code: 'Comma', lower: 'б', upper: 'Б', finger: 'right-middle' },
        { code: 'Period', lower: 'ю', upper: 'Ю', finger: 'right-ring' },
        { code: 'Slash', lower: '.', upper: ',', finger: 'right-pinky' },
    ],
    [
        {
            code: 'Space',
            lower: ' ',
            upper: ' ',
            finger: 'thumb',
        },
    ],
];

export const KEYBOARD_LAYOUTS: Record<Layout, LayoutKeys> = {
    QWERTY: QWERTY_KEYS,
    YCUKEN: YCUKEN_KEYS,
};
